name: Build QtIFW statically

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  USE_LIBARCHIVE: true

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      # fail-fast: Default is true, switch to false to allow one platform to fail and still run others
      fail-fast: false
      matrix:
        build_name: [apple-clang-15, apple-clang-15-armv8]
        include:
        - build_name: apple-clang-15
          os: macos-15-intel
          arch: x86_64
          SDKROOT: /Applications/Xcode_16.4.app
        - build_name: apple-clang-15-armv8
          os: macos-14
          arch: arm64
          SDKROOT: /Applications/Xcode_15.4.app

    steps:
    - name: setup
      id: setup-runner
      shell: bash
      run: |
        sudo xcode-select -switch "${{ matrix.SDKROOT }}"
        clang --version
        sdk_path=$(xcrun --sdk macosx --show-sdk-path)
        echo "sdk_path=$sdk_path" >> $GITHUB_ENV
        brew install ninja ccache coreutils
        if [[ "${{ env.USE_LIBARCHIVE }}" == "true" ]]; then
          brew install xz
        fi
        mkdir build-qt6
        mkdir build-ifw

        export CCACHE_DIR="${{ github.workspace }}/.ccache"
        echo "CCACHE_DIR=$CCACHE_DIR"
        echo "CCACHE_DIR=$CCACHE_DIR" >> $GITHUB_ENV
        echo "ccache-dir=$CCACHE_DIR" >> $GITHUB_OUTPUT
        ccache --set-config=cache_dir=$CCACHE_DIR
        ccache --set-config=max_size=2G
        ccache --set-config=compression=true
        ccache --set-config=sloppiness=pch_defines,time_macros
        ccache --set-config=compiler_check=content # darwin only
        ccache -p

        echo "CMAKE_C_COMPILER_LAUNCHER=ccache" >> $GITHUB_ENV
        echo "CMAKE_CXX_COMPILER_LAUNCHER=ccache" >> $GITHUB_ENV

    - name: Restore CCache cache
      uses: actions/cache/restore@v5
      id: cacheccache-restore
      with:
        path: |
          ${{ steps.setup-runner.outputs.ccache-dir }}
        key: ccache-qt6-6.9.1-${{ matrix.os }}-libarchive-${{ env.USE_LIBARCHIVE }}-${{ github.run_id }}
        restore-keys: |
          ccache-qt6-6.9.1-${{ matrix.os }}-libarchive-${{ env.USE_LIBARCHIVE }}-
          ccache-qt6-6.9.1-${{ matrix.os }}-

    - name: Checkout Qt6 repos
      shell: bash
      run: |
        git clone --depth 1 -b 6.9.1 https://github.com/qt/qt5.git qt6
        cd qt6
        perl init-repository --mirror https://github.com/qt/ --module-subset="qt5compat,qtbase,qtdeclarative,qttools,qttranslations,qtshadertools"
        # qyieldcpu: Fix compilation with macOS 26.4 SDK
        # qt6/qtbase/src/corelib/thread/qyieldcpu.h:37:5: error: implicitly declaring library function '__yield' with type 'void ()' [-Werror,-Wimplicit-function-declaration]
        cd qtbase
        git cherry-pick a76004f16fdc43e1b7af83bfdf3f1a613491b234
        cd ..

    - name: Configure Qt6 statically
      working-directory: build-qt6
      shell: bash
      run: |
        ../qt6/configure -prefix $PWD/qtbase -release -static -accessibility -qt-zlib -qt-libpng -no-cups -no-sql-sqlite -no-qml-debug -nomake examples -nomake tests -no-freetype -ccache

    - name: Build Qt6 statically
      working-directory: build-qt6
      shell: bash
      run: |
        ccache --zero-stats
        ninja
        ccache --show-stats

        echo "Install can't work"
        ninja install || true

    - name: Add Qt6 to PATH
      run: echo "${{ github.workspace }}/build-qt6/qtbase/bin" >> $GITHUB_PATH

    - name: Checkout installer-framework
      uses: actions/checkout@v6
      with:
        # Repository name with owner. For example, actions/checkout
        # Default: ${{ github.repository }}
        repository: 'jmarrec/installer-framework'
        ref: 'QTIFW-3084-more-4_11_0'
        path: 'installer-framework'

    - name: Build QTIFW
      working-directory: build-ifw
      shell: bash
      run: |
        begin_group() { echo -e "::group::\033[93m$1\033[0m"; }
        set -x

        begin_group "qmake version"
        qmake -version
        echo "::endgroup::"

        begin_group "QMake Configure"
        if [[ "${{ env.USE_LIBARCHIVE }}" == "true" ]]; then
          # I could pass IFW_LZMA_LIBRARY=$(brew --prefix xz)/lib/liblzma.a to statically link against liblzma
          # but If I don't it uses the system's /usr/lib/liblzma.5.dylib which is good
          # I do NOT want to pass "LIBS+=-L$(brew --prefix xz)/lib" because installerfw.pri will add "-llzma"
          # and it will link against the homebrew dynamic library which has different codesigning
          qmake CONFIG+=libarchive CONFIG+=ccache \
            INCLUDEPATH+=$(brew --prefix xz)/include \
            ../installer-framework/installerfw.pro
        else
          qmake CONFIG+=ccache ../installer-framework/installerfw.pro
        fi

        echo "::endgroup::"

        begin_group "Build"
        make -j $(nproc)
        echo "::endgroup::"

    - name: Save CCache cache
      if: always() && steps.cacheccache-restore.outputs.cache-hit != 'true'
      uses: actions/cache/save@v5
      with:
        path: |
          ${{ steps.setup-runner.outputs.ccache-dir }}
        key: ${{ steps.cacheccache-restore.outputs.cache-primary-key }}

    - name: Inspect installerbase version
      id: installerbase-version
      working-directory: build-ifw/bin
      shell: bash
      run: |
        set -x
        ./installerbase --version
        QTIFW_VERSION=$(./installerbase --version | grep -oE "[0-9]+(\.[0-9]+)*" | head -n1)
        echo "ifw_version=$QTIFW_VERSION" >> $GITHUB_OUTPUT

    - name: Verify no Homebrew dependencies
      working-directory: build-ifw/bin
      shell: bash
      run: |
        fail=0
        for exe in *; do
          bad=$(otool -L "$exe" | grep 'homebrew' || true)
          if [[ -n "$bad" ]]; then
            echo "ERROR: $exe has Homebrew dependency:"
            echo "$bad"
            fail=1
          fi
        done
        exit $fail

    - name: Zip binaries
      run: zip -j QtIFW-${{ steps.installerbase-version.outputs.ifw_version }}-${{ matrix.arch }}.zip build-ifw/bin/*

    - name: Archive binary artifacts
      uses: actions/upload-artifact@v7
      with:
        name: QtIFW-${{ steps.installerbase-version.outputs.ifw_version }}-${{ matrix.arch }}
        path: build-ifw/bin/*

    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v2
      if: github.event_name != 'pull_request'
      with:
        tag_name: ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || 'latest' }}
        name: ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || 'Latest (main)' }}
        prerelease: ${{ !startsWith(github.ref, 'refs/tags/') }}
        files: QtIFW-${{ steps.installerbase-version.outputs.ifw_version }}-${{ matrix.arch }}.zip
